/* ------------------------------------------------------------------
 * Minimal .xlsx reader - no dependencies.
 *
 * An .xlsx is a ZIP of XML. We unzip with the browser's own
 * DecompressionStream('deflate-raw') and pull the cells out with
 * regexes: the XML is machine-generated by Excel/Zoho and regular
 * enough that a parser would not buy us anything.
 *
 * The XML->grid half is pure so it can be tested under node.
 * ------------------------------------------------------------------ */
(function (root) {
  'use strict';

  // -- ZIP ------------------------------------------------------------
  const EOCD = 0x06054b50, CEN = 0x02014b50;

  function findEOCD(dv) {
    // The comment field can push it back up to 64 KB from the end.
    const min = Math.max(0, dv.byteLength - 66000);
    for (let i = dv.byteLength - 22; i >= min; i--) {
      if (dv.getUint32(i, true) === EOCD) return i;
    }
    return -1;
  }

  function entries(buf) {
    const dv = new DataView(buf);
    const eocd = findEOCD(dv);
    if (eocd < 0) throw new Error('Not a valid .xlsx file (no ZIP directory found).');
    const count = dv.getUint16(eocd + 10, true);
    let p = dv.getUint32(eocd + 16, true);
    const out = [];
    for (let i = 0; i < count; i++) {
      if (dv.getUint32(p, true) !== CEN) break;
      const method = dv.getUint16(p + 10, true);
      const compSize = dv.getUint32(p + 20, true);
      const nameLen = dv.getUint16(p + 28, true);
      const extraLen = dv.getUint16(p + 30, true);
      const cmtLen = dv.getUint16(p + 32, true);
      const localAt = dv.getUint32(p + 42, true);
      const name = new TextDecoder().decode(new Uint8Array(buf, p + 46, nameLen));
      out.push({ name, method, compSize, localAt });
      p += 46 + nameLen + extraLen + cmtLen;
    }
    return { dv, list: out };
  }

  async function inflate(bytes, method) {
    if (method === 0) return bytes;
    if (method !== 8) throw new Error('Unsupported ZIP compression in this file.');
    if (typeof DecompressionStream === 'undefined')
      throw new Error('This browser cannot unzip .xlsx - save the sheet as CSV instead.');
    const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));
    return new Uint8Array(await new Response(stream).arrayBuffer());
  }

  async function unzip(buf) {
    const { dv, list } = entries(buf);
    const files = {};
    for (const e of list) {
      // The local header repeats the name/extra lengths; data follows it.
      const nameLen = dv.getUint16(e.localAt + 26, true);
      const extraLen = dv.getUint16(e.localAt + 28, true);
      const start = e.localAt + 30 + nameLen + extraLen;
      const raw = new Uint8Array(buf, start, e.compSize);
      files[e.name] = new TextDecoder().decode(await inflate(raw, e.method));
    }
    return files;
  }

  // -- XML ------------------------------------------------------------
  const ENT = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };
  function unesc(s) {
    return s.replace(/&(#x?[0-9a-fA-F]+|amp|lt|gt|quot|apos);/g, (m, g) => {
      if (g[0] !== '#') return ENT[g] || m;
      const n = g[1] === 'x' || g[1] === 'X' ? parseInt(g.slice(2), 16) : parseInt(g.slice(1), 10);
      return isNaN(n) ? m : String.fromCodePoint(n);
    });
  }

  /* <si> may be one <t> or many <r><t> runs; concatenate them all. */
  function sharedStrings(xml) {
    if (!xml) return [];
    const out = [];
    const si = /<si\b[^>]*>([\s\S]*?)<\/si>/g;
    let m;
    while ((m = si.exec(xml))) {
      let text = '';
      const t = /<t\b[^>]*>([\s\S]*?)<\/t>/g;
      let n;
      while ((n = t.exec(m[1]))) text += unesc(n[1]);
      out.push(text);
    }
    return out;
  }

  /* "BV12" -> 73 (zero-based column index) */
  function colIndex(ref) {
    const letters = (ref.match(/^[A-Z]+/) || [''])[0];
    let n = 0;
    for (let i = 0; i < letters.length; i++) n = n * 26 + (letters.charCodeAt(i) - 64);
    return n - 1;
  }

  /* A NUMERIC CELL WRITTEN IN EXPONENTIAL FORM.

     Zoho stores phone numbers, ID numbers and payment references as numbers,
     and its xlsx writer serialises the large ones as "6.2895410887918E13" -
     a perfectly legal numeric cell. Passed downstream as that TEXT, every
     digit-taking helper reads the EXPONENT as part of the value:
     normPhone('6.281215303279E12') returned 628121530327912, which is the
     real thirteen-digit number with the "12" glued on the end.

     690 rows of the C1/D export carry the applicant's own phone that way, and
     341 of a 400-row sample came out as something CEAC refuses outright. It is
     also the true cause of the "stray digit" phone diagnosed - wrongly - as a
     data-entry error on 2026-09-01: +628195201137810 is a valid number plus a
     two-digit exponent.

     Expanded HERE, at the reader, so one change covers every column - mapped,
     unmapped and future - in both sheets. Only a NON-NEGATIVE exponent is
     touched, so a genuine tiny fraction is left exactly as written, and a
     plain date serial like 45848 never enters this branch at all. */
  function expandExp(text) {
    if (!/^[-+]?\d+(\.\d+)?[eE]\+?\d+$/.test(text)) return text;
    const n = Number(text);
    if (!isFinite(n)) return text;
    return Number.isInteger(n) ? n.toFixed(0) : String(n);
  }
  function sheetToGrid(xml, strings) {
    const grid = [];
    const rowRe = /<row\b[^>]*>([\s\S]*?)<\/row>/g;
    let r;
    while ((r = rowRe.exec(xml))) {
      const cells = [];
      const cellRe = /<c\b([^>]*)(?:\/>|>([\s\S]*?)<\/c>)/g;
      let c;
      while ((c = cellRe.exec(r[1]))) {
        const attrs = c[1] || '', body = c[2] || '';
        const ref = (attrs.match(/\br="([A-Z]+\d+)"/) || [])[1];
        const type = (attrs.match(/\bt="([^"]+)"/) || [])[1] || 'n';
        let value = '';
        if (type === 'inlineStr') {
          const t = /<t\b[^>]*>([\s\S]*?)<\/t>/g;
          let n;
          while ((n = t.exec(body))) value += unesc(n[1]);
        } else {
          const v = (body.match(/<v\b[^>]*>([\s\S]*?)<\/v>/) || [])[1];
          if (v !== undefined) {
            /* Only the numeric branch is expanded. A SHARED-STRING cell holding
               exponential-looking text is text somebody typed, and rewriting it
               would be a guess. */
            value = type === 's' ? (strings[+v] !== undefined ? strings[+v] : '')
                                 : expandExp(unesc(v));
          }
        }
        const at = ref ? colIndex(ref) : cells.length;
        while (cells.length < at) cells.push('');
        cells[at] = value;
      }
      grid.push(cells);
    }
    return grid;
  }

  /* Cell -> URL. Excel stores a link two ways, and the Supporting Letter
     column uses one of them, so both are read:
       <hyperlinks><hyperlink ref="CC5" r:id="rId1"/></hyperlinks>
         with the target in the sheet's own .rels file, and
       =HYPERLINK("https://...","label") as a formula in the cell.
     Without this the cell reads as empty and the link is lost. */
  function hyperlinks(sheetXml, relsXml) {
    const out = {};
    const rels = {};
    const relRe = /<Relationship\b[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g;
    let m;
    while ((m = relRe.exec(relsXml || ''))) rels[m[1]] = unesc(m[2]);

    const hRe = /<hyperlink\b([^>]*)\/?>/g;
    while ((m = hRe.exec(sheetXml || ''))) {
      const a = m[1];
      const ref = (a.match(/\bref="([^"]+)"/) || [])[1];
      const rid = (a.match(/r:id="([^"]+)"/) || [])[1];
      if (!ref) continue;
      const target = rid ? rels[rid] : unesc((a.match(/\blocation="([^"]*)"/) || [])[1] || '');
      if (target) out[ref.split(':')[0]] = target;
    }

    /* Walk cell by cell. A lazy gap between <c> and <f> would happily
       cross into the next cell and pin the formula to the wrong ref. */
    const cellRe = /<c\b([^>]*)(?:\/>|>([\s\S]*?)<\/c>)/g;
    while ((m = cellRe.exec(sheetXml || ''))) {
      const ref = (m[1].match(/\br="([A-Z]+\d+)"/) || [])[1];
      if (!ref || out[ref]) continue;
      const f = (m[2] || '').match(/<f\b[^>]*>([\s\S]*?)<\/f>/);
      if (!f) continue;
      const url = unesc(f[1]).match(/HYPERLINK\s*\(\s*"([^"]+)"/i);
      if (url) out[ref] = url[1];
    }
    return out;
  }

  /* Sheet name -> the worksheet part it lives in. */
  function sheetTargets(workbookXml, relsXml) {
    const rels = {};
    const relRe = /<Relationship\b[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g;
    let m;
    while ((m = relRe.exec(relsXml || ''))) rels[m[1]] = m[2];

    const out = [];
    const shRe = /<sheet\b([^>]*)\/?>/g;
    while ((m = shRe.exec(workbookXml || ''))) {
      const a = m[1];
      const name = unesc((a.match(/\bname="([^"]*)"/) || [])[1] || '');
      const rid = (a.match(/r:id="([^"]+)"/) || [])[1];
      let target = rels[rid] || '';
      if (target && target[0] !== '/') target = 'xl/' + target.replace(/^\.\//, '');
      out.push({ name, target: target.replace(/^\//, '') });
    }
    return out;
  }

  // -- entry point -----------------------------------------------------
  async function read(buf, preferredSheet) {
    const files = await unzip(buf);
    const strings = sharedStrings(files['xl/sharedStrings.xml']);
    const sheets = sheetTargets(files['xl/workbook.xml'], files['xl/_rels/workbook.xml.rels']);

    let pick = null;
    if (preferredSheet) {
      pick = sheets.find(s => s.name.toLowerCase() === preferredSheet.toLowerCase());
    }
    if (!pick) pick = sheets.find(s => files[s.target]) || sheets[0];
    if (!pick) throw new Error('No worksheet found inside the .xlsx file.');

    const part = files[pick.target] ? pick.target : 'xl/worksheets/sheet1.xml';
    const xml = files[part];
    if (!xml) throw new Error('Could not read worksheet "' + pick.name + '".');

    const relPart = part.replace(/([^/]+)$/, '_rels/$1.rels');
    return {
      name: pick.name,
      grid: sheetToGrid(xml, strings),
      links: hyperlinks(xml, files[relPart]),
      sheets: sheets.map(s => s.name),
    };
  }

  const api = { read, unzip, sharedStrings, sheetToGrid, expandExp, sheetTargets, hyperlinks, colIndex, unesc };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.XLSXLite = api;
})(typeof self !== 'undefined' ? self : this);
