/* ------------------------------------------------------------------
 * Minimal .xlsx reader - no dependencies.
 *
 * An .xlsx is a ZIP of XML. We unzip with the browser's own
 * DecompressionStream('deflate-raw') and pull the cells out with
 * regexes: the XML is machine-generated by Excel/Zoho and regular
 * enough that a parser would not buy us anything.
 *
 * The XML->grid half is pure so it can be tested under node.
 * ------------------------------------------------------------------ */
(function (root) {
  'use strict';

  // -- ZIP ------------------------------------------------------------
  const EOCD = 0x06054b50, CEN = 0x02014b50;

  function findEOCD(dv) {
    // The comment field can push it back up to 64 KB from the end.
    const min = Math.max(0, dv.byteLength - 66000);
    for (let i = dv.byteLength - 22; i >= min; i--) {
      if (dv.getUint32(i, true) === EOCD) return i;
    }
    return -1;
  }

  function entries(buf) {
    const dv = new DataView(buf);
    const eocd = findEOCD(dv);
    if (eocd < 0) throw new Error('Not a valid .xlsx file (no ZIP directory found).');
    const count = dv.getUint16(eocd + 10, true);
    let p = dv.getUint32(eocd + 16, true);
    const out = [];
    for (let i = 0; i < count; i++) {
      if (dv.getUint32(p, true) !== CEN) break;
      const method = dv.getUint16(p + 10, true);
      const compSize = dv.getUint32(p + 20, true);
      const nameLen = dv.getUint16(p + 28, true);
      const extraLen = dv.getUint16(p + 30, true);
      const cmtLen = dv.getUint16(p + 32, true);
      const localAt = dv.getUint32(p + 42, true);
      const name = new TextDecoder().decode(new Uint8Array(buf, p + 46, nameLen));
      out.push({ name, method, compSize, localAt });
      p += 46 + nameLen + extraLen + cmtLen;
    }
    return { dv, list: out };
  }

  async function inflate(bytes, method) {
    if (method === 0) return bytes;
    if (method !== 8) throw new Error('Unsupported ZIP compression in this file.');
    if (typeof DecompressionStream === 'undefined')
      throw new Error('This browser cannot unzip .xlsx - save the sheet as CSV instead.');
    const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));
    return new Uint8Array(await new Response(stream).arrayBuffer());
  }

  async function unzip(buf) {
    const { dv, list } = entries(buf);
    const files = {};
    for (const e of list) {
      // The local header repeats the name/extra lengths; data follows it.
      const nameLen = dv.getUint16(e.localAt + 26, true);
      const extraLen = dv.getUint16(e.localAt + 28, true);
      const start = e.localAt + 30 + nameLen + extraLen;
      const raw = new Uint8Array(buf, start, e.compSize);
      files[e.name] = new TextDecoder().decode(await inflate(raw, e.method));
    }
    return files;
  }

  // -- XML ------------------------------------------------------------
  const ENT = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };
  function unesc(s) {
    return s.replace(/&(#x?[0-9a-fA-F]+|amp|lt|gt|quot|apos);/g, (m, g) => {
      if (g[0] !== '#') return ENT[g] || m;
      const n = g[1] === 'x' || g[1] === 'X' ? parseInt(g.slice(2), 16) : parseInt(g.slice(1), 10);
      return isNaN(n) ? m : String.fromCodePoint(n);
    });
  }

  /* <si> may be one <t> or many <r><t> runs; concatenate them all. */
  function sharedStrings(xml) {
    if (!xml) return [];
    const out = [];
    const si = /<si\b[^>]*>([\s\S]*?)<\/si>/g;
    let m;
    while ((m = si.exec(xml))) {
      let text = '';
      const t = /<t\b[^>]*>([\s\S]*?)<\/t>/g;
      let n;
      while ((n = t.exec(m[1]))) text += unesc(n[1]);
      out.push(text);
    }
    return out;
  }

  /* "BV12" -> 73 (zero-based column index) */
  function colIndex(ref) {
    const letters = (ref.match(/^[A-Z]+/) || [''])[0];
    let n = 0;
    for (let i = 0; i < letters.length; i++) n = n * 26 + (letters.charCodeAt(i) - 64);
    return n - 1;
  }

  function sheetToGrid(xml, strings) {
    const grid = [];
    const rowRe = /<row\b[^>]*>([\s\S]*?)<\/row>/g;
    let r;
    while ((r = rowRe.exec(xml))) {
      const cells = [];
      const cellRe = /<c\b([^>]*)(?:\/>|>([\s\S]*?)<\/c>)/g;
      let c;
      while ((c = cellRe.exec(r[1]))) {
        const attrs = c[1] || '', body = c[2] || '';
        const ref = (attrs.match(/\br="([A-Z]+\d+)"/) || [])[1];
        const type = (attrs.match(/\bt="([^"]+)"/) || [])[1] || 'n';
        let value = '';
        if (type === 'inlineStr') {
          const t = /<t\b[^>]*>([\s\S]*?)<\/t>/g;
          let n;
          while ((n = t.exec(body))) value += unesc(n[1]);
        } else {
          const v = (body.match(/<v\b[^>]*>([\s\S]*?)<\/v>/) || [])[1];
          if (v !== undefined) {
            value = type === 's' ? (strings[+v] !== undefined ? strings[+v] : '') : unesc(v);
          }
        }
        const at = ref ? colIndex(ref) : cells.length;
        while (cells.length < at) cells.push('');
        cells[at] = value;
      }
      grid.push(cells);
    }
    return grid;
  }

  /* Sheet name -> the worksheet part it lives in. */
  function sheetTargets(workbookXml, relsXml) {
    const rels = {};
    const relRe = /<Relationship\b[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g;
    let m;
    while ((m = relRe.exec(relsXml || ''))) rels[m[1]] = m[2];

    const out = [];
    const shRe = /<sheet\b([^>]*)\/?>/g;
    while ((m = shRe.exec(workbookXml || ''))) {
      const a = m[1];
      const name = unesc((a.match(/\bname="([^"]*)"/) || [])[1] || '');
      const rid = (a.match(/r:id="([^"]+)"/) || [])[1];
      let target = rels[rid] || '';
      if (target && target[0] !== '/') target = 'xl/' + target.replace(/^\.\//, '');
      out.push({ name, target: target.replace(/^\//, '') });
    }
    return out;
  }

  // -- entry point -----------------------------------------------------
  async function read(buf, preferredSheet) {
    const files = await unzip(buf);
    const strings = sharedStrings(files['xl/sharedStrings.xml']);
    const sheets = sheetTargets(files['xl/workbook.xml'], files['xl/_rels/workbook.xml.rels']);

    let pick = null;
    if (preferredSheet) {
      pick = sheets.find(s => s.name.toLowerCase() === preferredSheet.toLowerCase());
    }
    if (!pick) pick = sheets.find(s => files[s.target]) || sheets[0];
    if (!pick) throw new Error('No worksheet found inside the .xlsx file.');

    const xml = files[pick.target] || files['xl/worksheets/sheet1.xml'];
    if (!xml) throw new Error('Could not read worksheet "' + pick.name + '".');
    return { name: pick.name, grid: sheetToGrid(xml, strings), sheets: sheets.map(s => s.name) };
  }

  const api = { read, unzip, sharedStrings, sheetToGrid, sheetTargets, colIndex, unesc };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.XLSXLite = api;
})(typeof self !== 'undefined' ? self : this);
